### PR TITLE
Transmitter

### PR DESCRIPTION
**Pull request by CansWang**
quarter-rate mux optimized, DFF stages reduced by 1

### CODE REVIEW

**Comment by sgherbst** [comment]
@CansWang thanks, I will take a look at this now.

**Comment by zamyers** [comment]
Email me when you guys merge this request :)

**Review by CansWang — COMMENTED** [review]
> Email me when you guys merge this request :)

Sure, 
Thanks for the note

**Comment by sgherbst** [comment]
@zamyers if the tests pass on the latest commit, then I'll merge the PR around midnight.  Otherwise I would expect it to be merged Thursday morning.

**Comment by zamyers** [comment]
Thanks for letting me know!

**Review by sgherbst — APPROVED** [review]
LGTM

**Pull request merged**
