### PR TITLE
dcore hot fix

### PR DESCRIPTION
**Pull request by sjkim85**
one of inputs of output buffer in digital_core is fixed 
 - del_out_rep[1] is tied to 0 to prevent floating gate drc error.

### CODE REVIEW

**Review by CansWang — COMMENTED** [review]
Sorry for the typo, 
This will also affect the tx_top,
I will pull the latest commits from the git and add corresponding connection fixes related to the MUX.

**Comment by sgherbst** [comment]
@sjkim85 should we close this PR now that PR #156 has been merged?

**Comment by sgherbst** [comment]
@sjkim85 can this PR be closed?  (i.e., has it already been merged or is it included in PR #159 ?)  Thanks!

**Comment by sgherbst** [comment]
Closing as I believe this was already included in a previous PR.

**Pull request closed without merging**
